---
### Wait for Tower to be responsive
- name: Wait for Tower to be responsive
  uri:
    url: https://localhost/api/v2/ping/
    method: GET
    user: admin
    password: "{{admin_password}}"
    validate_certs: false
    force_basic_auth: true
  register: test_ping
  until: test_ping is not failed
  retries: 10

#### INVENTORY
- name: create workshop inventory
  tower_inventory:
    name: "Workshop Inventory"
    organization: "Default"
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: false

- name: import inventory
  shell: 'tower-manage inventory_import --source=/home/{{ username }}/lab_inventory/hosts --inventory-name="Workshop Inventory"'
#### END OF INVENTORY

#### CREDENTIAL
- name: add SSH credential into Ansible Tower
  tower_credential:
    username: ec2-user
    name: "Workshop Credential"
    ssh_key_data: "{{ lookup('file', playbook_dir +'/' + ec2_name_prefix + '/' + ec2_name_prefix + '-private.pem') }}"
    kind: ssh
    organization: "Default"
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: false

- name: add tower credential into ansible tower
  tower_credential:
    host: "{{ansible_host}}"
    username: admin
    password: "{{admin_password}}"
    name: "Tower Credential"
    kind: tower
    organization: Default
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: false
#### END OF CREDENTIAL

#### REMOVE BUILT-IN DEMO CONTENT
- name: delete demo job template
  tower_job_template:
    name: "Demo Job Template"
    job_type: "run"
    project: "Demo Project"
    playbook: "hello_world.yml"
    state: absent
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: false

- name: remove demo credential
  tower_credential:
    username: admin
    name: "Demo Credential"
    kind: ssh
    state: absent
    organization: ""
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: false

- name: remove demo inventory
  tower_inventory:
    name: "Demo Inventory"
    organization: "Default"
    state: absent
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: false

- name: remove built-in tower project
  tower_project:
    name: "Demo Project"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/ansible-tower-samples"
    state: absent
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: false
#### END OF REMOVE BUILT-IN DEMO CONTENT

- name: setup workshop specific tower information
  include_tasks: "{{item}}"
  with_first_found:
    - "{{role_path}}/tasks/{{workshop_type}}.yml"
    - "{{role_path}}/tasks/unsupported_workshop.yml"
