---
- name: Remove AWS kep-pair to re-launch workshop without removing everything else
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: set keys for instance creation dynamically since key was not supplied by user
      set_fact:
        ec2_key_name: "{{ ec2_name_prefix }}-key"

    - name: delete ssh key pair for workshop {{ ec2_name_prefix }}
      ec2_key:
        name: "{{ec2_key_name}}"
        region: "{{ ec2_region }}"
        state: absent